-- Generated by scripts/generate-world-cup-seed.mjs.
-- Sources: FIFA match-centre links embedded in the 2026 World Cup group pages.

alter table public.teams
  add column if not exists fifa_code text,
  add column if not exists fifa_rank integer;

alter table public.matches
  add column if not exists match_number integer;

create unique index if not exists teams_fifa_code_key
  on public.teams (fifa_code);

create unique index if not exists matches_match_number_key
  on public.matches (match_number);

insert into public.teams (fifa_code, name, group_name, flag_url, fifa_rank)
values
  ('MEX', 'México', 'A', '/flags/mex.svg', 14),
  ('RSA', 'Sudáfrica', 'A', '/flags/rsa.svg', 60),
  ('KOR', 'Corea del Sur', 'A', '/flags/kor.svg', 25),
  ('CZE', 'Chequia', 'A', '/flags/cze.svg', 40),
  ('CAN', 'Canadá', 'B', '/flags/can.svg', 30),
  ('SUI', 'Suiza', 'B', '/flags/sui.svg', 19),
  ('QAT', 'Catar', 'B', '/flags/qat.svg', 56),
  ('BIH', 'Bosnia y Herzegovina', 'B', '/flags/bih.svg', 64),
  ('BRA', 'Brasil', 'C', '/flags/bra.svg', 6),
  ('MAR', 'Marruecos', 'C', '/flags/mar.svg', 7),
  ('HAI', 'Haití', 'C', '/flags/hai.svg', 83),
  ('SCO', 'Escocia', 'C', '/flags/sco.svg', 42),
  ('USA', 'Estados Unidos', 'D', '/flags/usa.svg', 17),
  ('PAR', 'Paraguay', 'D', '/flags/par.svg', 41),
  ('AUS', 'Australia', 'D', '/flags/aus.svg', 27),
  ('TUR', 'Turquía', 'D', '/flags/tur.svg', 22),
  ('GER', 'Alemania', 'E', '/flags/ger.svg', 10),
  ('CUW', 'Curazao', 'E', '/flags/cuw.svg', 82),
  ('CIV', 'Costa de Marfil', 'E', '/flags/civ.svg', 33),
  ('ECU', 'Ecuador', 'E', '/flags/ecu.svg', 23),
  ('NED', 'Países Bajos', 'F', '/flags/ned.svg', 8),
  ('JPN', 'Japón', 'F', '/flags/jpn.svg', 18),
  ('SWE', 'Suecia', 'F', '/flags/swe.svg', 38),
  ('TUN', 'Túnez', 'F', '/flags/tun.svg', 45),
  ('BEL', 'Bélgica', 'G', '/flags/bel.svg', 9),
  ('EGY', 'Egipto', 'G', '/flags/egy.svg', 29),
  ('IRN', 'Irán', 'G', '/flags/irn.svg', 20),
  ('NZL', 'Nueva Zelanda', 'G', '/flags/nzl.svg', 85),
  ('ESP', 'España', 'H', '/flags/esp.svg', 2),
  ('CPV', 'Cabo Verde', 'H', '/flags/cpv.svg', 67),
  ('KSA', 'Arabia Saudita', 'H', '/flags/ksa.svg', 61),
  ('URU', 'Uruguay', 'H', '/flags/uru.svg', 16),
  ('FRA', 'Francia', 'I', '/flags/fra.svg', 3),
  ('SEN', 'Senegal', 'I', '/flags/sen.svg', 15),
  ('IRQ', 'Irak', 'I', '/flags/irq.svg', 57),
  ('NOR', 'Noruega', 'I', '/flags/nor.svg', 31),
  ('ARG', 'Argentina', 'J', '/flags/arg.svg', 1),
  ('ALG', 'Argelia', 'J', '/flags/alg.svg', 28),
  ('AUT', 'Austria', 'J', '/flags/aut.svg', 24),
  ('JOR', 'Jordania', 'J', '/flags/jor.svg', 63),
  ('POR', 'Portugal', 'K', '/flags/por.svg', 5),
  ('COD', 'RD del Congo', 'K', '/flags/cod.svg', 46),
  ('UZB', 'Uzbekistán', 'K', '/flags/uzb.svg', 50),
  ('COL', 'Colombia', 'K', '/flags/col.svg', 13),
  ('ENG', 'Inglaterra', 'L', '/flags/eng.svg', 4),
  ('CRO', 'Croacia', 'L', '/flags/cro.svg', 11),
  ('GHA', 'Ghana', 'L', '/flags/gha.svg', 73),
  ('PAN', 'Panamá', 'L', '/flags/pan.svg', 34)
on conflict (fifa_code) do update
set
  name = excluded.name,
  group_name = excluded.group_name,
  flag_url = excluded.flag_url,
  fifa_rank = excluded.fifa_rank;

with fixture_data (
  match_number,
  phase,
  group_name,
  home_team_code,
  away_team_code,
  match_date,
  home_score,
  away_score,
  status
) as (
  values
  (1, 'group_stage', 'A', 'MEX', 'RSA', '2026-06-11T19:00:00.000Z'::timestamptz, 2, 0, 'finished'),
  (2, 'group_stage', 'A', 'KOR', 'CZE', '2026-06-12T02:00:00.000Z'::timestamptz, 2, 1, 'finished'),
  (3, 'group_stage', 'B', 'CAN', 'BIH', '2026-06-12T19:00:00.000Z'::timestamptz, 1, 1, 'finished'),
  (4, 'group_stage', 'D', 'USA', 'PAR', '2026-06-13T01:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (5, 'group_stage', 'C', 'HAI', 'SCO', '2026-06-14T01:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (6, 'group_stage', 'D', 'AUS', 'TUR', '2026-06-14T04:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (7, 'group_stage', 'C', 'BRA', 'MAR', '2026-06-13T22:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (8, 'group_stage', 'B', 'QAT', 'SUI', '2026-06-13T19:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (9, 'group_stage', 'E', 'CIV', 'ECU', '2026-06-14T23:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (10, 'group_stage', 'E', 'GER', 'CUW', '2026-06-14T17:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (11, 'group_stage', 'F', 'NED', 'JPN', '2026-06-14T20:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (12, 'group_stage', 'F', 'SWE', 'TUN', '2026-06-15T02:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (13, 'group_stage', 'H', 'KSA', 'URU', '2026-06-15T22:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (14, 'group_stage', 'H', 'ESP', 'CPV', '2026-06-15T16:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (15, 'group_stage', 'G', 'IRN', 'NZL', '2026-06-16T01:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (16, 'group_stage', 'G', 'BEL', 'EGY', '2026-06-15T19:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (17, 'group_stage', 'I', 'FRA', 'SEN', '2026-06-16T19:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (18, 'group_stage', 'I', 'IRQ', 'NOR', '2026-06-16T22:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (19, 'group_stage', 'J', 'ARG', 'ALG', '2026-06-17T01:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (20, 'group_stage', 'J', 'AUT', 'JOR', '2026-06-17T04:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (21, 'group_stage', 'L', 'GHA', 'PAN', '2026-06-17T23:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (22, 'group_stage', 'L', 'ENG', 'CRO', '2026-06-17T20:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (23, 'group_stage', 'K', 'POR', 'COD', '2026-06-17T17:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (24, 'group_stage', 'K', 'UZB', 'COL', '2026-06-18T02:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (25, 'group_stage', 'A', 'CZE', 'RSA', '2026-06-18T16:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (26, 'group_stage', 'B', 'SUI', 'BIH', '2026-06-18T19:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (27, 'group_stage', 'B', 'CAN', 'QAT', '2026-06-18T22:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (28, 'group_stage', 'A', 'MEX', 'KOR', '2026-06-19T01:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (29, 'group_stage', 'C', 'BRA', 'HAI', '2026-06-20T00:30:00.000Z'::timestamptz, null, null, 'scheduled'),
  (30, 'group_stage', 'C', 'SCO', 'MAR', '2026-06-19T22:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (31, 'group_stage', 'D', 'TUR', 'PAR', '2026-06-20T03:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (32, 'group_stage', 'D', 'USA', 'AUS', '2026-06-19T19:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (33, 'group_stage', 'E', 'GER', 'CIV', '2026-06-20T20:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (34, 'group_stage', 'E', 'ECU', 'CUW', '2026-06-21T00:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (35, 'group_stage', 'F', 'NED', 'SWE', '2026-06-20T17:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (36, 'group_stage', 'F', 'TUN', 'JPN', '2026-06-21T04:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (37, 'group_stage', 'H', 'URU', 'CPV', '2026-06-21T22:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (38, 'group_stage', 'H', 'ESP', 'KSA', '2026-06-21T16:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (39, 'group_stage', 'G', 'BEL', 'IRN', '2026-06-21T19:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (40, 'group_stage', 'G', 'NZL', 'EGY', '2026-06-22T01:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (41, 'group_stage', 'I', 'NOR', 'SEN', '2026-06-23T00:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (42, 'group_stage', 'I', 'FRA', 'IRQ', '2026-06-22T21:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (43, 'group_stage', 'J', 'ARG', 'AUT', '2026-06-22T17:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (44, 'group_stage', 'J', 'JOR', 'ALG', '2026-06-23T03:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (45, 'group_stage', 'L', 'ENG', 'GHA', '2026-06-23T20:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (46, 'group_stage', 'L', 'PAN', 'CRO', '2026-06-23T23:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (47, 'group_stage', 'K', 'POR', 'UZB', '2026-06-23T17:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (48, 'group_stage', 'K', 'COL', 'COD', '2026-06-24T02:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (49, 'group_stage', 'C', 'SCO', 'BRA', '2026-06-24T22:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (50, 'group_stage', 'C', 'MAR', 'HAI', '2026-06-24T22:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (51, 'group_stage', 'B', 'SUI', 'CAN', '2026-06-24T19:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (52, 'group_stage', 'B', 'BIH', 'QAT', '2026-06-24T19:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (53, 'group_stage', 'A', 'CZE', 'MEX', '2026-06-25T01:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (54, 'group_stage', 'A', 'RSA', 'KOR', '2026-06-25T01:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (55, 'group_stage', 'E', 'CUW', 'CIV', '2026-06-25T20:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (56, 'group_stage', 'E', 'ECU', 'GER', '2026-06-25T20:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (57, 'group_stage', 'F', 'JPN', 'SWE', '2026-06-25T23:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (58, 'group_stage', 'F', 'TUN', 'NED', '2026-06-25T23:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (59, 'group_stage', 'D', 'TUR', 'USA', '2026-06-26T02:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (60, 'group_stage', 'D', 'PAR', 'AUS', '2026-06-26T02:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (61, 'group_stage', 'I', 'NOR', 'FRA', '2026-06-26T19:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (62, 'group_stage', 'I', 'SEN', 'IRQ', '2026-06-26T19:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (63, 'group_stage', 'G', 'EGY', 'IRN', '2026-06-27T03:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (64, 'group_stage', 'G', 'NZL', 'BEL', '2026-06-27T03:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (65, 'group_stage', 'H', 'CPV', 'KSA', '2026-06-27T00:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (66, 'group_stage', 'H', 'URU', 'ESP', '2026-06-27T00:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (67, 'group_stage', 'L', 'PAN', 'ENG', '2026-06-27T21:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (68, 'group_stage', 'L', 'CRO', 'GHA', '2026-06-27T21:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (69, 'group_stage', 'J', 'ALG', 'AUT', '2026-06-28T02:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (70, 'group_stage', 'J', 'JOR', 'ARG', '2026-06-28T02:00:00.000Z'::timestamptz, null, null, 'scheduled'),
  (71, 'group_stage', 'K', 'COL', 'POR', '2026-06-27T23:30:00.000Z'::timestamptz, null, null, 'scheduled'),
  (72, 'group_stage', 'K', 'COD', 'UZB', '2026-06-27T23:30:00.000Z'::timestamptz, null, null, 'scheduled')
)
insert into public.matches (
  match_number,
  phase,
  group_name,
  home_team_id,
  away_team_id,
  match_date,
  home_score,
  away_score,
  winner_team_id,
  status
)
select
  fixture_data.match_number,
  fixture_data.phase::public.match_phase,
  fixture_data.group_name,
  home_team.id,
  away_team.id,
  fixture_data.match_date,
  fixture_data.home_score,
  fixture_data.away_score,
  case
    when fixture_data.home_score > fixture_data.away_score then home_team.id
    when fixture_data.away_score > fixture_data.home_score then away_team.id
    else null
  end,
  fixture_data.status::public.match_status
from fixture_data
join public.teams home_team
  on home_team.fifa_code = fixture_data.home_team_code
join public.teams away_team
  on away_team.fifa_code = fixture_data.away_team_code
on conflict (match_number) do update
set
  phase = excluded.phase,
  group_name = excluded.group_name,
  home_team_id = excluded.home_team_id,
  away_team_id = excluded.away_team_id,
  match_date = excluded.match_date,
  home_score = excluded.home_score,
  away_score = excluded.away_score,
  winner_team_id = excluded.winner_team_id,
  status = excluded.status;
